version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: dbt
      POSTGRES_PASSWORD: dbt
      POSTGRES_DB: jaffle_shop
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "dbt"]
      interval: 5s
      retries: 5
    restart: unless-stopped
    ports:
      - 5432:5432