jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: dbt
      pass: dbt
      port: 5432
      dbname: jaffle_shop
      schema: dbt_dev
      threads: 4
    prod:
      type: postgres
      host: localhost
      user: dbt
      pass: dbt
      port: 5432
      dbname: jaffle_shop
      schema: dbt
      threads: 4